version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: urban-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urban_companion
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: urban-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
